/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.dorif.handler;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.11.0)", date = "2018-11-03")
public class DocTermInfo implements org.apache.thrift.TBase<DocTermInfo, DocTermInfo._Fields>, java.io.Serializable, Cloneable, Comparable<DocTermInfo> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("DocTermInfo");

  private static final org.apache.thrift.protocol.TField ID_FIELD_DESC = new org.apache.thrift.protocol.TField("id", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField TERM_FIELD_DESC = new org.apache.thrift.protocol.TField("term", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField DOC_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("docName", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField FREQUENCY_FIELD_DESC = new org.apache.thrift.protocol.TField("frequency", org.apache.thrift.protocol.TType.I64, (short)4);
  private static final org.apache.thrift.protocol.TField TF_FIELD_DESC = new org.apache.thrift.protocol.TField("tf", org.apache.thrift.protocol.TType.DOUBLE, (short)5);
  private static final org.apache.thrift.protocol.TField TFIDF_FIELD_DESC = new org.apache.thrift.protocol.TField("tfidf", org.apache.thrift.protocol.TType.DOUBLE, (short)6);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new DocTermInfoStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new DocTermInfoTupleSchemeFactory();

  public long id; // required
  public java.lang.String term; // required
  public java.lang.String docName; // required
  public long frequency; // required
  public double tf; // required
  public double tfidf; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ID((short)1, "id"),
    TERM((short)2, "term"),
    DOC_NAME((short)3, "docName"),
    FREQUENCY((short)4, "frequency"),
    TF((short)5, "tf"),
    TFIDF((short)6, "tfidf");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ID
          return ID;
        case 2: // TERM
          return TERM;
        case 3: // DOC_NAME
          return DOC_NAME;
        case 4: // FREQUENCY
          return FREQUENCY;
        case 5: // TF
          return TF;
        case 6: // TFIDF
          return TFIDF;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ID_ISSET_ID = 0;
  private static final int __FREQUENCY_ISSET_ID = 1;
  private static final int __TF_ISSET_ID = 2;
  private static final int __TFIDF_ISSET_ID = 3;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ID, new org.apache.thrift.meta_data.FieldMetaData("id", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.TERM, new org.apache.thrift.meta_data.FieldMetaData("term", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DOC_NAME, new org.apache.thrift.meta_data.FieldMetaData("docName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.FREQUENCY, new org.apache.thrift.meta_data.FieldMetaData("frequency", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.TF, new org.apache.thrift.meta_data.FieldMetaData("tf", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.TFIDF, new org.apache.thrift.meta_data.FieldMetaData("tfidf", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(DocTermInfo.class, metaDataMap);
  }

  public DocTermInfo() {
  }

  public DocTermInfo(
    long id,
    java.lang.String term,
    java.lang.String docName,
    long frequency,
    double tf,
    double tfidf)
  {
    this();
    this.id = id;
    setIdIsSet(true);
    this.term = term;
    this.docName = docName;
    this.frequency = frequency;
    setFrequencyIsSet(true);
    this.tf = tf;
    setTfIsSet(true);
    this.tfidf = tfidf;
    setTfidfIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public DocTermInfo(DocTermInfo other) {
    __isset_bitfield = other.__isset_bitfield;
    this.id = other.id;
    if (other.isSetTerm()) {
      this.term = other.term;
    }
    if (other.isSetDocName()) {
      this.docName = other.docName;
    }
    this.frequency = other.frequency;
    this.tf = other.tf;
    this.tfidf = other.tfidf;
  }

  public DocTermInfo deepCopy() {
    return new DocTermInfo(this);
  }

  @Override
  public void clear() {
    setIdIsSet(false);
    this.id = 0;
    this.term = null;
    this.docName = null;
    setFrequencyIsSet(false);
    this.frequency = 0;
    setTfIsSet(false);
    this.tf = 0.0;
    setTfidfIsSet(false);
    this.tfidf = 0.0;
  }

  public long getId() {
    return this.id;
  }

  public DocTermInfo setId(long id) {
    this.id = id;
    setIdIsSet(true);
    return this;
  }

  public void unsetId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ID_ISSET_ID);
  }

  /** Returns true if field id is set (has been assigned a value) and false otherwise */
  public boolean isSetId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ID_ISSET_ID);
  }

  public void setIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ID_ISSET_ID, value);
  }

  public java.lang.String getTerm() {
    return this.term;
  }

  public DocTermInfo setTerm(java.lang.String term) {
    this.term = term;
    return this;
  }

  public void unsetTerm() {
    this.term = null;
  }

  /** Returns true if field term is set (has been assigned a value) and false otherwise */
  public boolean isSetTerm() {
    return this.term != null;
  }

  public void setTermIsSet(boolean value) {
    if (!value) {
      this.term = null;
    }
  }

  public java.lang.String getDocName() {
    return this.docName;
  }

  public DocTermInfo setDocName(java.lang.String docName) {
    this.docName = docName;
    return this;
  }

  public void unsetDocName() {
    this.docName = null;
  }

  /** Returns true if field docName is set (has been assigned a value) and false otherwise */
  public boolean isSetDocName() {
    return this.docName != null;
  }

  public void setDocNameIsSet(boolean value) {
    if (!value) {
      this.docName = null;
    }
  }

  public long getFrequency() {
    return this.frequency;
  }

  public DocTermInfo setFrequency(long frequency) {
    this.frequency = frequency;
    setFrequencyIsSet(true);
    return this;
  }

  public void unsetFrequency() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __FREQUENCY_ISSET_ID);
  }

  /** Returns true if field frequency is set (has been assigned a value) and false otherwise */
  public boolean isSetFrequency() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __FREQUENCY_ISSET_ID);
  }

  public void setFrequencyIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __FREQUENCY_ISSET_ID, value);
  }

  public double getTf() {
    return this.tf;
  }

  public DocTermInfo setTf(double tf) {
    this.tf = tf;
    setTfIsSet(true);
    return this;
  }

  public void unsetTf() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __TF_ISSET_ID);
  }

  /** Returns true if field tf is set (has been assigned a value) and false otherwise */
  public boolean isSetTf() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __TF_ISSET_ID);
  }

  public void setTfIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __TF_ISSET_ID, value);
  }

  public double getTfidf() {
    return this.tfidf;
  }

  public DocTermInfo setTfidf(double tfidf) {
    this.tfidf = tfidf;
    setTfidfIsSet(true);
    return this;
  }

  public void unsetTfidf() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __TFIDF_ISSET_ID);
  }

  /** Returns true if field tfidf is set (has been assigned a value) and false otherwise */
  public boolean isSetTfidf() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __TFIDF_ISSET_ID);
  }

  public void setTfidfIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __TFIDF_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case ID:
      if (value == null) {
        unsetId();
      } else {
        setId((java.lang.Long)value);
      }
      break;

    case TERM:
      if (value == null) {
        unsetTerm();
      } else {
        setTerm((java.lang.String)value);
      }
      break;

    case DOC_NAME:
      if (value == null) {
        unsetDocName();
      } else {
        setDocName((java.lang.String)value);
      }
      break;

    case FREQUENCY:
      if (value == null) {
        unsetFrequency();
      } else {
        setFrequency((java.lang.Long)value);
      }
      break;

    case TF:
      if (value == null) {
        unsetTf();
      } else {
        setTf((java.lang.Double)value);
      }
      break;

    case TFIDF:
      if (value == null) {
        unsetTfidf();
      } else {
        setTfidf((java.lang.Double)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case ID:
      return getId();

    case TERM:
      return getTerm();

    case DOC_NAME:
      return getDocName();

    case FREQUENCY:
      return getFrequency();

    case TF:
      return getTf();

    case TFIDF:
      return getTfidf();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case ID:
      return isSetId();
    case TERM:
      return isSetTerm();
    case DOC_NAME:
      return isSetDocName();
    case FREQUENCY:
      return isSetFrequency();
    case TF:
      return isSetTf();
    case TFIDF:
      return isSetTfidf();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof DocTermInfo)
      return this.equals((DocTermInfo)that);
    return false;
  }

  public boolean equals(DocTermInfo that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_id = true;
    boolean that_present_id = true;
    if (this_present_id || that_present_id) {
      if (!(this_present_id && that_present_id))
        return false;
      if (this.id != that.id)
        return false;
    }

    boolean this_present_term = true && this.isSetTerm();
    boolean that_present_term = true && that.isSetTerm();
    if (this_present_term || that_present_term) {
      if (!(this_present_term && that_present_term))
        return false;
      if (!this.term.equals(that.term))
        return false;
    }

    boolean this_present_docName = true && this.isSetDocName();
    boolean that_present_docName = true && that.isSetDocName();
    if (this_present_docName || that_present_docName) {
      if (!(this_present_docName && that_present_docName))
        return false;
      if (!this.docName.equals(that.docName))
        return false;
    }

    boolean this_present_frequency = true;
    boolean that_present_frequency = true;
    if (this_present_frequency || that_present_frequency) {
      if (!(this_present_frequency && that_present_frequency))
        return false;
      if (this.frequency != that.frequency)
        return false;
    }

    boolean this_present_tf = true;
    boolean that_present_tf = true;
    if (this_present_tf || that_present_tf) {
      if (!(this_present_tf && that_present_tf))
        return false;
      if (this.tf != that.tf)
        return false;
    }

    boolean this_present_tfidf = true;
    boolean that_present_tfidf = true;
    if (this_present_tfidf || that_present_tfidf) {
      if (!(this_present_tfidf && that_present_tfidf))
        return false;
      if (this.tfidf != that.tfidf)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(id);

    hashCode = hashCode * 8191 + ((isSetTerm()) ? 131071 : 524287);
    if (isSetTerm())
      hashCode = hashCode * 8191 + term.hashCode();

    hashCode = hashCode * 8191 + ((isSetDocName()) ? 131071 : 524287);
    if (isSetDocName())
      hashCode = hashCode * 8191 + docName.hashCode();

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(frequency);

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(tf);

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(tfidf);

    return hashCode;
  }

  @Override
  public int compareTo(DocTermInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetId()).compareTo(other.isSetId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.id, other.id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetTerm()).compareTo(other.isSetTerm());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTerm()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.term, other.term);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetDocName()).compareTo(other.isSetDocName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDocName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.docName, other.docName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetFrequency()).compareTo(other.isSetFrequency());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFrequency()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.frequency, other.frequency);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetTf()).compareTo(other.isSetTf());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTf()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tf, other.tf);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetTfidf()).compareTo(other.isSetTfidf());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTfidf()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tfidf, other.tfidf);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("DocTermInfo(");
    boolean first = true;

    sb.append("id:");
    sb.append(this.id);
    first = false;
    if (!first) sb.append(", ");
    sb.append("term:");
    if (this.term == null) {
      sb.append("null");
    } else {
      sb.append(this.term);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("docName:");
    if (this.docName == null) {
      sb.append("null");
    } else {
      sb.append(this.docName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("frequency:");
    sb.append(this.frequency);
    first = false;
    if (!first) sb.append(", ");
    sb.append("tf:");
    sb.append(this.tf);
    first = false;
    if (!first) sb.append(", ");
    sb.append("tfidf:");
    sb.append(this.tfidf);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class DocTermInfoStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public DocTermInfoStandardScheme getScheme() {
      return new DocTermInfoStandardScheme();
    }
  }

  private static class DocTermInfoStandardScheme extends org.apache.thrift.scheme.StandardScheme<DocTermInfo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, DocTermInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.id = iprot.readI64();
              struct.setIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // TERM
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.term = iprot.readString();
              struct.setTermIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // DOC_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.docName = iprot.readString();
              struct.setDocNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // FREQUENCY
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.frequency = iprot.readI64();
              struct.setFrequencyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // TF
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.tf = iprot.readDouble();
              struct.setTfIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // TFIDF
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.tfidf = iprot.readDouble();
              struct.setTfidfIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, DocTermInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(ID_FIELD_DESC);
      oprot.writeI64(struct.id);
      oprot.writeFieldEnd();
      if (struct.term != null) {
        oprot.writeFieldBegin(TERM_FIELD_DESC);
        oprot.writeString(struct.term);
        oprot.writeFieldEnd();
      }
      if (struct.docName != null) {
        oprot.writeFieldBegin(DOC_NAME_FIELD_DESC);
        oprot.writeString(struct.docName);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(FREQUENCY_FIELD_DESC);
      oprot.writeI64(struct.frequency);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(TF_FIELD_DESC);
      oprot.writeDouble(struct.tf);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(TFIDF_FIELD_DESC);
      oprot.writeDouble(struct.tfidf);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class DocTermInfoTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public DocTermInfoTupleScheme getScheme() {
      return new DocTermInfoTupleScheme();
    }
  }

  private static class DocTermInfoTupleScheme extends org.apache.thrift.scheme.TupleScheme<DocTermInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, DocTermInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetId()) {
        optionals.set(0);
      }
      if (struct.isSetTerm()) {
        optionals.set(1);
      }
      if (struct.isSetDocName()) {
        optionals.set(2);
      }
      if (struct.isSetFrequency()) {
        optionals.set(3);
      }
      if (struct.isSetTf()) {
        optionals.set(4);
      }
      if (struct.isSetTfidf()) {
        optionals.set(5);
      }
      oprot.writeBitSet(optionals, 6);
      if (struct.isSetId()) {
        oprot.writeI64(struct.id);
      }
      if (struct.isSetTerm()) {
        oprot.writeString(struct.term);
      }
      if (struct.isSetDocName()) {
        oprot.writeString(struct.docName);
      }
      if (struct.isSetFrequency()) {
        oprot.writeI64(struct.frequency);
      }
      if (struct.isSetTf()) {
        oprot.writeDouble(struct.tf);
      }
      if (struct.isSetTfidf()) {
        oprot.writeDouble(struct.tfidf);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, DocTermInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(6);
      if (incoming.get(0)) {
        struct.id = iprot.readI64();
        struct.setIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.term = iprot.readString();
        struct.setTermIsSet(true);
      }
      if (incoming.get(2)) {
        struct.docName = iprot.readString();
        struct.setDocNameIsSet(true);
      }
      if (incoming.get(3)) {
        struct.frequency = iprot.readI64();
        struct.setFrequencyIsSet(true);
      }
      if (incoming.get(4)) {
        struct.tf = iprot.readDouble();
        struct.setTfIsSet(true);
      }
      if (incoming.get(5)) {
        struct.tfidf = iprot.readDouble();
        struct.setTfidfIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

